sudo: required

language: python

services:
  - docker

before_install:
  - docker pull gabrielmmats/impress

install:
  - pip3 install coveralls

script:
  - docker run -t -it -v $PWD:/test gabrielmmats/impress bash
  - cd /home
  - ls

after_success:
  - coveralls
